[versions]
agp = "7.3.1"
kotlin = "1.7.20"
coroutines = "1.6.4"

androidxhilt = "1.0.0"
androidxlifecycle = "2.5.1"
desugarJdkLibs = "1.1.8"
detekt = "1.22.0"
junit = "5.9.2"
ksp = "1.7.20-1.0.8"
room = "2.5.0"
mockK = "1.13.3"
sqliteJdbc = "3.40.0.0"
timber = "5.0.1"
truth = "1.1.3"
versionsGradlePlugin = "0.44.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = "com.android.tools:desugar_jdk_libs:1.2.2"

androidx-appcompat = "androidx.appcompat:appcompat:1.6.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

kotlin-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.3.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradlePlugin" }

xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }

