[versions]
agp = "7.3.0"
kotlin = "1.7.20"
coroutines = "1.6.4"

androidxhilt = "1.0.0"
androidxlifecycle = "2.5.1"
desugarJdkLibs = "1.1.8"
detekt = "1.21.0"
ksp = "1.7.20-1.0.6"
room = "2.5.0-beta01"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = "com.android.tools:desugar_jdk_libs:1.1.8"

androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.1" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.9.1" }

kotlin-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.3.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

mockK = "io.mockk:mockk:1.13.2"

timber = "com.jakewharton.timber:timber:5.0.1"

truth = "com.google.truth:truth:1.1.3"

gradleVersions-gradlePluginClasspath = "com.github.ben-manes:gradle-versions-plugin:0.42.0"

xerial-sqlite = "org.xerial:sqlite-jdbc:3.39.3.0"
