[versions]
agp = "8.0.2"
kotlin = "1.8.21"
coroutines = "1.7.1"

androidxlifecycle = "2.6.1"
desugarJdkLibs = "2.0.3"
detekt = "1.23.0"
junit = "5.9.3"
ksp = "1.8.21-1.0.11"
room = "2.6.0-alpha02"
mockK = "1.13.5"
sqliteJdbc = "3.42.0.0"
timber = "5.0.1"
truth = "1.1.5"
versionsGradlePlugin = "0.47.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradlePlugin" }

xerial-sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
